### ISSUE TITLE
MosML fails to build on OpenBSD 5.6 in a different way

### ISSUE THREAD

**Issue by Athas** [kfl/mosml#28]
After using the fix mentioned in the sibling issue, `make world` can proceed to this far more exciting error:

    ld -o camlrunm prims.o interp.o expand.o misc.o stacks.o fix_code.o main.o fail.o signals.o freelist.o major_gc.o minor_gc.o memory.o alloc.o roots.o compare.o ints.o floats.o str.o io.o extern.o externcp.o intern.o interncp.o hash.o sys.o meta.o parsing.o lexing.o gc_ctrl.o mosml.o unix.o runtime.o md5sum.o callback.o dynlib.o -lm 
    interp.o(.text+0x1c): In function `interprete':
    : undefined reference to `__guard_local'
    ld: final link failed: Bad value
